"""Markdown and JSON report generation."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np

from forecaster.data import StockData
from forecaster.model import ForecastResult
from forecaster.analysis import RiskMetrics, ForecastSignal

DISCLAIMER = (
    "> **DISCLAIMER**: This tool is for **educational and research purposes only**. "
    "It is **NOT financial advice**. Stock forecasting models—including foundation "
    "models—cannot reliably predict future prices. Always do your own research and "
    "consult a qualified financial advisor before investing."
)


def generate_markdown_report(
    stock: StockData,
    result: ForecastResult,
    risk: RiskMetrics,
    signal: ForecastSignal,
    output_path: Optional[Path] = None,
    chart_path: Optional[Path] = None,
) -> str:
    """Produce a full Markdown report for a single ticker forecast."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    mc = stock.metadata.get("marketCap")
    mc_str = f"${mc / 1e6:.1f}M" if mc else "N/A"
    name = stock.metadata.get("longName", stock.ticker)
    sector = stock.metadata.get("sector", "N/A")
    industry = stock.metadata.get("industry", "N/A")
    beta_str = f"{risk.beta_to_spy:.2f}" if risk.beta_to_spy else "N/A"

    signal_icon = {"BULLISH": "🟢", "BEARISH": "🔴", "NEUTRAL": "🟡"}.get(signal.signal, "⚪")

    chart_embed = ""
    if chart_path:
        chart_embed = f"\n![{stock.ticker} Forecast]({chart_path.name})\n"

    md = f"""# {name} ({stock.ticker}) — TimesFM Forecast Report

Generated: {now}

{DISCLAIMER}

---

## Company Overview

| Field | Value |
|-------|-------|
| Ticker | `{stock.ticker}` |
| Company | {name} |
| Sector | {sector} |
| Industry | {industry} |
| Market Cap | {mc_str} ({stock.market_cap_category}) |
| Exchange | {stock.metadata.get("exchange", "N/A")} |
| 52-Week Range | ${stock.metadata.get("52wLow", "N/A")} – ${stock.metadata.get("52wHigh", "N/A")} |
| Beta | {beta_str} |

---

## Forecast Summary ({result.horizon}-Day Horizon)

| Metric | Value |
|--------|-------|
| Last Close | ${result.last_known_price:.4f} |
| Point Forecast (end) | ${result.point_forecast[-1]:.4f} |
| Expected Return | {result.expected_return_pct:+.2f}% |
| 80% CI Low (10th pct) | ${result.lower_80[-1]:.4f} ({result.downside_pct:+.1f}%) |
| 80% CI High (90th pct) | ${result.upper_80[-1]:.4f} ({result.upside_pct:+.1f}%) |
| Median Forecast | ${result.median[-1]:.4f} |

{chart_embed}

---

## Signal {signal_icon}

**{signal.signal}** — {signal.confidence} confidence

"""
    for r in signal.rationale:
        md += f"- {r}\n"

    md += f"""
---

## Risk Metrics

| Metric | Value |
|--------|-------|
| Annualised Volatility | {risk.annualised_volatility:.1f}% |
| Sharpe Ratio (4.5% RF) | {risk.sharpe_ratio:.2f} |
| Max Drawdown | {risk.max_drawdown:.1f}% |
| 20-Day Momentum | {risk.momentum_20d:+.1f}% |
| RSI (14) | {risk.rsi_14:.1f} |
| Avg Daily Range | {risk.avg_daily_range_pct:.2f}% |
| Volume Spike | {"Yes ⚠️" if risk.volume_spike else "No"} |

---

## Model Info

- **Model**: Google TimesFM 2.5 (200M params, PyTorch)
- **Architecture**: Decoder-only time-series foundation model
- **Training**: Pretrained on large-scale real-world time series
- **Context used**: {min(len(stock.close), 512)} trading days
- **Quantile levels**: {result.quantile_levels}

---

*Report generated by [timesfm-smallcap-forecaster](https://github.com/Abhi183/timesfm-smallcap-forecaster)*
"""

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(md)

    return md


def generate_json_report(
    stock: StockData,
    result: ForecastResult,
    risk: RiskMetrics,
    signal: ForecastSignal,
    output_path: Optional[Path] = None,
) -> dict:
    """Produce a machine-readable JSON report."""
    data = {
        "generated_at": datetime.now().isoformat(),
        "ticker": stock.ticker,
        "company": stock.metadata.get("longName", stock.ticker),
        "market_cap": stock.metadata.get("marketCap"),
        "market_cap_category": stock.market_cap_category,
        "forecast": {
            "horizon_days": result.horizon,
            "last_close": result.last_known_price,
            "point_forecast": result.point_forecast.tolist(),
            "median_forecast": result.median.tolist(),
            "lower_80": result.lower_80.tolist(),
            "upper_80": result.upper_80.tolist(),
            "expected_return_pct": result.expected_return_pct,
            "upside_pct_80ci": result.upside_pct,
            "downside_pct_80ci": result.downside_pct,
        },
        "signal": {
            "direction": signal.signal,
            "confidence": signal.confidence,
            "rationale": signal.rationale,
        },
        "risk": {
            "annualised_volatility_pct": risk.annualised_volatility,
            "sharpe_ratio": risk.sharpe_ratio,
            "max_drawdown_pct": risk.max_drawdown,
            "momentum_20d_pct": risk.momentum_20d,
            "rsi_14": risk.rsi_14,
            "avg_daily_range_pct": risk.avg_daily_range_pct,
            "volume_spike": risk.volume_spike,
            "beta": risk.beta_to_spy,
        },
    }

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(json.dumps(data, indent=2))

    return data
